/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UiAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UiButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UiCalendar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UiCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UiChip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Chip.vue')['default']
    UiDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UiModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UiOverlayProvider: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue')['default']
    UiPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UiSlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UiTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UiTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
