/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UiBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UiButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UiCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UiIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UiPagination: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UiTable: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UiTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.28.0_@inertiajs+vue3@2.0.11_vue@3.5.16_typescript@5.8.3__9fe15abbb572b1ac9df8a32795f3b71e/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
